### ISSUE TITLE
I am not getting correct bounding box after inferencing.

### ISSUE THREAD

**Issue by charchit7** [robustsam/RobustSAM#3]
I manually checked the bounding box. 
But while doing the inference with the same bbox. I am getting an differerent bounding box. Could you please tell me why is that the case. 

![Screenshot 2024-06-26 at 10 56 59 AM](https://github.com/robustsam/RobustSAM/assets/21178353/49ed3279-9496-47d9-8075-f82c81d6c2ef)
![results_sofa](https://github.com/robustsam/RobustSAM/assets/21178353/be13eac3-c30d-4e8c-b88f-c49bc5a11033)

**Comment by robustsam** [comment]
We need to perform transformation on input image in order to match the size requirements of model (please refer to L89 of eval.py), I think that's the cause of your problem.

**Comment by charchit7** [comment]
Closing, you are write, I made a mistake. Thank you for your work :)
