### ISSUE TITLE
Do you have any vit_h checkpoint?

### ISSUE THREAD

**Issue by meysam-kazemi340** [robustsam/RobustSAM#5]
I click on the link to download Checkpoint, but there is only one file, when I use this file for vit_h, I get an error.
Do you have any vit_h checkpoint?

**Comment by robustsam** [comment]
Thanks for your interest! The other checkpoints will be organized and released along with the training codes and dataset.

**Comment by robustsam** [comment]
Hi there,

We have released other checkpoints. Thanks for your patience.

**Comment by meysam-kazemi340** [comment]
thanks
