### ISSUE TITLE
Regarding FGMBlock

### ISSUE THREAD

**Issue by liuch37** [robustsam/RobustSAM#7]
Thank you for your great work! As I went through ```FGMBlock```, I don't see IFFT operation being implemented. Should this line https://github.com/robustsam/RobustSAM/blob/eee0a3115c934c28e2dd8bd46bc21d83b9647675/robust_segment_anything/modeling/components.py#L220 be implemented as below?

```
x = torch.real(torch.fft.ifft2(modified_fft_map, dim=(-2,-1)))
return x
```
Thanks.

**Comment by Yi-Heng** [comment]
I also want to ask this question！

**Comment by robustsam** [comment]
@liuch37  Thanks for pointing out the missing implementation. The related [code](https://github.com/robustsam/RobustSAM/blob/main/robust_segment_anything/modeling/components.py) and the [checkpoint link](https://github.com/robustsam/RobustSAM#:~:text=Download%20pretrained%20RobustSAM%20checkpoint%20and%20place%20into%20current%20directory) in the README have been updated.

**Comment by liuch37** [comment]
Thanks much!
